<?php

/** @var $block \Moogento\Sitemap\Block\Adminhtml\System\Config\Hint */ ?>

<div class="moogento-notice">
    <div class="floatingcows">
        <div class="floatingsheep" style="background-image:url(<?= $block->getLogo() ?>);">
            <a href="https://moogento.com/" id="mooink">&nbsp;</a>
        </div>
        <div id="mooinfo">
            <h4>
                <a target="_blank" href="https://moogento.com/sitemap">Sitemap</a>
            </h4>
            <div id="moo_license_info">
                <ul class="ext_info" style="width: 32em;">
                    <li class="tick">
                        <em></em> You're running version <span style="opacity:0.5;float:right;"><?= $block->getVersion() ?></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <ul id="wikilinks">
        <li><a class="wiki" href="https://moogento.com/guides"><span>★</span> User Guide</a></li>
        <li><a class="store" href="https://moogento.com"><img src="https://moogento.com/images/moogento-favicon_32x32.png" width=16 /> Add Superpowers!</a></li>
    </ul>
</div>
<div style="clear:both;"></div>