<?php
/**
 * Copyright © Moogento. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
?>

<div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
    <h1 class="page-title">
        Sitemap
    </h1>
    <?= $block->getChildHtml() ?>
    <div class="sitemap-search" data-bind="scope: 'filterable-list'">
        <label for="search-name"></label>
        <input type="text" class="search" id="search-name" placeholder="<?= __('Search') ?>"
               data-bind="textInput: findText, event:{ change: findInSitemap.bind( $data, findText() )}"/>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "filterable-list": {
                        "component": "Moogento_Sitemap/js/filterable-list"
                    }
                }
            }
        }
    }
</script>
